apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: default  # ← ajoute ton namespace ici (ex: argo-apps ou autre)
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
