apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: test-namespace
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80         # Port d'exposition du service
      targetPort: 80   # Port du container
  type: LoadBalancer

